apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: appsso-starter-java
  labels:
    app.kubernetes.io/part-of: appsso-starter-java
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: appsso-starter-java
spec:
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/live-update: "true"
        autoscaling.knative.dev/maxScale: "1"
        autoscaling.knative.dev/minScale: "1"
        boot.spring.io/version: 2.6.6
        conventions.apps.tanzu.vmware.com/applied-conventions: |-
          developer-conventions/live-update-convention
          developer-conventions/add-source-image-label
          spring-boot-convention/spring-boot
          spring-boot-convention/spring-boot-graceful-shutdown
          spring-boot-convention/spring-boot-web
          appliveview-sample/app-live-view-appflavour-check
        developer.apps.tanzu.vmware.com/image-source-digest: main/1f6d9c665066914ca0fe537bab029350321b4d64
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: appsso-starter-java
        apps.tanzu.vmware.com/workload-type: web
        carto.run/workload-name: appsso-starter-java
        conventions.apps.tanzu.vmware.com/framework: spring-boot
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: -Dserver.port="8080" -Dserver.shutdown.grace-period="24s"
        image: kadashizzle.azurecr.us/tapootbbasic/appsso-starter-java-dev@sha256:360a7400518936f363a9bc79e5d0d0481493c41850b9144f7106e99b762cc6f9
        name: workload
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: default

